### ISSUE TITLE
Breaks with later d3 versions

### ISSUE THREAD

**Issue by dcollien** [geekplux/markvis-pie#1]
From:
https://github.com/d3/d3/blob/master/CHANGES.md

D3 no longer provides the d3.schemeCategory20* categorical color schemes. These twenty-color schemes were flawed because their grouped design could falsely imply relationships in the data: a shared hue can imply that the encoded data are part of a group (a super-category), while relative lightness can imply order. Instead, D3 now includes d3-scale-chromatic, which implements excellent schemes from ColorBrewer, including categorical, diverging, sequential single-hue and sequential multi-hue schemes. These schemes are available in both discrete and continuous variants.

**Comment by geekplux** [comment]
fixed by #2
